# Generated by Django 3.2.15 on 2022-08-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='car_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
