# Generated by Django 3.2.15 on 2022-08-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contactus_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
