# Generated by Django 3.2.15 on 2022-08-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220817_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='last_name',
        ),
    ]
